module.exports = [
  {
    title: 'Conecta Desenvolvendo Saúde',
    id: 'http://www.conecta-desenvolvendosaude.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Saúde',
    ano: 2018,
    produto: 'Site',
  },
  {
    title: 'Bazílio Soluções Digitais',
    id: 'http://www.bazilio.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Contabilidade',
    ano: 2019,
    produto: 'Site',
  },
  {
    title: 'C.E.E Centro Educacional Evolução',
    id: 'http://www.cee.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Educação',
    ano: 2019,
    produto: 'Site',
  },
  {
    title: 'UNICA Base Forte',
    id: 'http://www.unicabaseforte.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Associação',
    ano: 2019,
    produto: 'Site',
  },
  {
    title: 'UNICA Base Forte',
    id: 'http://www.unicabaseforte.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Associação',
    ano: 2019,
    produto: 'Sistema Web',
  },
  {
    title: 'UNICA Base Forte',
    id: 'http://www.unicabaseforte.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Associação',
    ano: 2019,
    produto: 'App Mobile',
  },
  {
    title: 'Dra. Marina Moura',
    id: 'http://www.dramarinamoura.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Saúde',
    ano: 2019,
    produto: 'Site',
  },
  {
    title: 'Azul Crédito Financeira',
    id: 'http://www.azulcreditofinanceira.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Financeira',
    ano: 2020,
    produto: 'Site',
  },
  {
    title: 'Incluir Terapias Integradas',
    id: 'http://www.incluirterapias.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Saúde',
    ano: 2021,
    produto: 'Site',
  },
  {
    title: 'Domínio Qualificação Profissional',
    id: 'http://www.dominioqualificacao.com.br/',
    thumb: '/img/thumb.jpeg',
    tipo: 'Educação',
    ano: 2022,
    produto: 'Site',
  },
];
